global using System;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using static Console_Monsters.Statics;
global using static Console_Monsters.BattleSystem;
global using Console_Monsters.Items;
global using Console_Monsters.Maps;
global using Console_Monsters.Monsters;
global using Console_Monsters.Bases;
global using Console_Monsters.Characters;
global using Console_Monsters.Screens;
global using Console_Monsters.Screens.Menus;
global using Console_Monsters.Enums;
global using Console_Monsters.Utilities;
global using System.Collections.Generic;
global using Towel;
global using static Towel.Statics;
