blank_issues_enabled: true
contact_links:
  - name: New Game Suggestion
    url: https://github.com/ZacharyPatten/dotnet-console-games/issues/17
    about: Suggest an idea for a new game.
  - name: Question
    url: https://github.com/ZacharyPatten/dotnet-console-games/discussions/new?category=q-a
    about: Ask a question.
  - name: Chat
    url: https://discord.gg/4XbQbwF
    about: Chat with the developers on Discord.