name: Dice Game Build
on:
  push:
    paths:
    - 'Projects/Dice Game/**'
    branches:
    - main
  pull_request:
    paths:
    - 'Projects/Dice Game/**'
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: dotnet build
      run: dotnet build "Projects\Dice Game\Dice Game.csproj" --configuration Release
