name: Tower Of Hanoi Build
on:
  push:
    paths:
    - 'Projects/Tower Of Hanoi/**'
    paths-ignore:
    - '**.md'
  pull_request:
    paths:
    - 'Projects/Tower Of Hanoi/**'
    paths-ignore:
    - '**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet build
      run: dotnet build "Projects\Tower Of Hanoi\Tower Of Hanoi.csproj" --configuration Release
