name: Type Build
on:
  push:
    paths:
    - 'Projects/Type/**'
  pull_request:
    paths:
    - 'Projects/Type/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet build
      run: dotnet build "Projects\Type\Type.csproj" --configuration Release
